version: '3.1'

services:
  db:
    image: postgres:14
    container_name: postgres_server
    build: ./postgresql
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=hogehoge
    restart: always